import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import PostSubmit from "../components/PostSubmit";
import Feed from "../components/Feed";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [title, setTitle] = useState("");
  async function getTitle() {
    const res = await fetch("http://localhost:3000/api/hello");
    const data = await res.json();
    setTitle(data.title);
  }

  useEffect(() => {
    getTitle();
  }, []);
  return (
    <>
      <Head>
        <title>E-Connect Feed!</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 viewport-fit=cover"
        />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className=" bg-light-primary">
        <NavBar />
        <Feed />
        <PostSubmit />
      </main>
    </>
  );
}
